version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Pulling java docker.
          command: |
            docker pull java:7
      - run:
          name: Create class file using java docker.
          command: |
            docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javac -d . FirstJava.java
      - run:
          name: Compiling and Executing java class files using java docker.
          command: |
            docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 java FirstJava
      - run:
          name: Displaying java class.
          command: |
            docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javap FirstJava