version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: java:7
    steps:
      - checkout
      - run: ps aux | grep docker
      - run: docker ps -a
      - run: javac -d . sample.java
      - run: java smplProg.sample