version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: java:7
    steps:
      - checkout
      - run: ps aux | grep docker
      - run: java -version
      - run: javac -classpath .;~/app smplProg.sample.java
      - run: java smplProg.sample