 version: 2
 jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk-stretch
     steps:
       - checkout
       - run: javac -version
       - run: javac D:\Personal Docs\repoforcirclici\src\test\java\FirstJava.java
#       - run: javac FirstJava.java
#       - run: java FirstJava
#       - run: javap FirstJava