 version: 2
 jobs:
   build:
#     working_directory: /repoforcirclici
     docker:
 #      - image: circleci/openjdk:8-jdk-stretch
       - image: java:7
     steps:
       - checkout
       - run: javac -d . FirstJava.java
       - run: java -d FirstJava