 version: 2
 jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk-stretch
     steps:
       - checkout
       - run:
           command: |
             cd src/test/java
             CLASSNAMES=$(circleci tests glob "**/*.java" \